"""add temporada table

Revision ID: 2f511dac1d7d
Revises: 03ea166506ae
Create Date: 2025-12-14 18:43:39.534759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f511dac1d7d'
down_revision = '03ea166506ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tabla_posiciones',
    sa.Column('id_equipo', sa.Integer(), nullable=False),
    sa.Column('nombre_equipo', sa.String(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('partidos_jugados', sa.Integer(), nullable=True),
    sa.Column('partidos_ganados', sa.Integer(), nullable=True),
    sa.Column('partidos_empatados', sa.Integer(), nullable=True),
    sa.Column('partidos_perdidos', sa.Integer(), nullable=True),
    sa.Column('goles_a_favor', sa.Integer(), nullable=True),
    sa.Column('goles_en_contra', sa.Integer(), nullable=True),
    sa.Column('cantidad_puntos', sa.Integer(), nullable=True),
    sa.Column('diferencia_gol', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_equipo')
    )
    op.drop_table('fase')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fase',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('orden', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('fase_pkey')),
    sa.UniqueConstraint('nombre', name=op.f('fase_nombre_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('tabla_posiciones')
    # ### end Alembic commands ###
