"""add temporada table

Revision ID: 4071372e63cb
Revises: 2f511dac1d7d
Create Date: 2025-12-14 18:59:00.648756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4071372e63cb'
down_revision = '2f511dac1d7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fase',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('orden', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('fase_pkey')),
    sa.UniqueConstraint('nombre', name=op.f('fase_nombre_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('torneo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('temporada_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporada.id'], name=op.f('torneo_temporada_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('torneo_pkey')),
    sa.UniqueConstraint('nombre', 'temporada_id', name=op.f('uq_torneo_temporada'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
