"""add columna orden e ida_vuelta a tabla Fase

Revision ID: 41e35a9679f7
Revises: 9b1bf61a6175
Create Date: 2025-12-14 22:05:08.671747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41e35a9679f7'
down_revision = '9b1bf61a6175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ida_vuelta', sa.Boolean(), nullable=False))
        batch_op.alter_column('torneo_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fase', schema=None) as batch_op:
        batch_op.alter_column('torneo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('ida_vuelta')

    # ### end Alembic commands ###
