"""Estado actual inicial

Revision ID: 74f386c9fc82
Revises: 
Create Date: 2026-03-03 13:49:47.119054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74f386c9fc82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    """op.create_table('tabla_posiciones',
    sa.Column('id_equipo', sa.Integer(), nullable=False),
    sa.Column('nombre_equipo', sa.String(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('partidos_jugados', sa.Integer(), nullable=True),
    sa.Column('partidos_ganados', sa.Integer(), nullable=True),
    sa.Column('partidos_empatados', sa.Integer(), nullable=True),
    sa.Column('partidos_perdidos', sa.Integer(), nullable=True),
    sa.Column('goles_a_favor', sa.Integer(), nullable=True),
    sa.Column('goles_en_contra', sa.Integer(), nullable=True),
    sa.Column('cantidad_puntos', sa.Integer(), nullable=True),
    sa.Column('diferencia_gol', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_equipo')
    )
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_equipo_club_categoria'))"""

    with op.batch_alter_table('partido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('penales_local', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('penales_visitante', sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column(
                'definido_por_penales',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false()
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partido', schema=None) as batch_op:
        batch_op.drop_column('definido_por_penales')
        batch_op.drop_column('penales_visitante')
        batch_op.drop_column('penales_local')

    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_equipo_club_categoria'), ['club_id', 'categoria'], unique=True)

    op.drop_table('tabla_posiciones')
    # ### end Alembic commands ###
