"""agrego activo a torneo

Revision ID: 7bdb8ecc6d06
Revises: 22103de68abf
Create Date: 2026-03-06 02:29:19.786945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bdb8ecc6d06'
down_revision = '22103de68abf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('torneo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('torneo', schema=None) as batch_op:
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
