"""add columna torneo_id a la tabla fase

Revision ID: 9b1bf61a6175
Revises: b53b0d1fb57a
Create Date: 2025-12-14 21:31:46.850103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b1bf61a6175'
down_revision = 'b53b0d1fb57a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tabla_posiciones',
    sa.Column('id_equipo', sa.Integer(), nullable=False),
    sa.Column('nombre_equipo', sa.String(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('partidos_jugados', sa.Integer(), nullable=True),
    sa.Column('partidos_ganados', sa.Integer(), nullable=True),
    sa.Column('partidos_empatados', sa.Integer(), nullable=True),
    sa.Column('partidos_perdidos', sa.Integer(), nullable=True),
    sa.Column('goles_a_favor', sa.Integer(), nullable=True),
    sa.Column('goles_en_contra', sa.Integer(), nullable=True),
    sa.Column('cantidad_puntos', sa.Integer(), nullable=True),
    sa.Column('diferencia_gol', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_equipo')
    )
    with op.batch_alter_table('fase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('torneo_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'torneo', ['torneo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fase', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('torneo_id')

    op.drop_table('tabla_posiciones')
    # ### end Alembic commands ###
