"""schema inicial

Revision ID: b2590735fdaa
Revises: 
Create Date: 2025-12-15 18:03:16.679962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2590735fdaa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('localidad', sa.String(length=120), nullable=True),
    sa.Column('escudo_url', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tabla_posiciones',
    sa.Column('id_equipo', sa.Integer(), nullable=False),
    sa.Column('nombre_equipo', sa.String(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('partidos_jugados', sa.Integer(), nullable=True),
    sa.Column('partidos_ganados', sa.Integer(), nullable=True),
    sa.Column('partidos_empatados', sa.Integer(), nullable=True),
    sa.Column('partidos_perdidos', sa.Integer(), nullable=True),
    sa.Column('goles_a_favor', sa.Integer(), nullable=True),
    sa.Column('goles_en_contra', sa.Integer(), nullable=True),
    sa.Column('cantidad_puntos', sa.Integer(), nullable=True),
    sa.Column('diferencia_gol', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_equipo')
    )
    op.create_table('temporada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('contraseña', sa.String(length=300), nullable=False),
    sa.Column('rol', sa.String(length=30), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('equipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'categoria', name='uq_equipo_club_categoria')
    )
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.create_index('ix_equipo_club_categoria', ['club_id', 'categoria'], unique=False)

    op.create_table('jugador',
    sa.Column('numero_carnet', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.PrimaryKeyConstraint('numero_carnet'),
    sa.UniqueConstraint('nombre', 'apellido', 'club_id', name='uq_jugador_nombre_apellido_club')
    )
    op.create_table('noticia',
    sa.Column('id_noticia', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=False),
    sa.Column('id_autor', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('imagen_url', sa.String(length=400), nullable=True),
    sa.Column('slug', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['id_autor'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_noticia'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('torneo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('temporada_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporada.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video',
    sa.Column('id_video', sa.Integer(), nullable=False),
    sa.Column('titulo_video', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_subida', sa.DateTime(), nullable=False),
    sa.Column('id_autor', sa.Integer(), nullable=False),
    sa.Column('jornada_jugada', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_autor'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_video')
    )
    op.create_table('fase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('torneo_id', sa.Integer(), nullable=False),
    sa.Column('ida_vuelta', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['torneo_id'], ['torneo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jugador_equipo',
    sa.Column('numero_carnet', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipo.id'], ),
    sa.ForeignKeyConstraint(['numero_carnet'], ['jugador.numero_carnet'], ),
    sa.PrimaryKeyConstraint('numero_carnet', 'equipo_id')
    )
    op.create_table('partido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_partido', sa.Date(), nullable=True),
    sa.Column('hora_partido', sa.Time(), nullable=True),
    sa.Column('jornada', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=20), nullable=False),
    sa.Column('torneo_id', sa.Integer(), nullable=True),
    sa.Column('fase_id', sa.Integer(), nullable=True),
    sa.Column('equipo_local_id', sa.Integer(), nullable=False),
    sa.Column('equipo_visitante_id', sa.Integer(), nullable=False),
    sa.Column('goles_local', sa.Integer(), nullable=False),
    sa.Column('goles_visitante', sa.Integer(), nullable=False),
    sa.Column('jugado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['equipo_local_id'], ['equipo.id'], ),
    sa.ForeignKeyConstraint(['equipo_visitante_id'], ['equipo.id'], ),
    sa.ForeignKeyConstraint(['fase_id'], ['fase.id'], ),
    sa.ForeignKeyConstraint(['torneo_id'], ['torneo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estado_jugador_partido',
    sa.Column('id_jugador', sa.Integer(), nullable=False),
    sa.Column('id_partido', sa.Integer(), nullable=False),
    sa.Column('cant_goles', sa.Integer(), nullable=False),
    sa.Column('tarjetas_amarillas', sa.Integer(), nullable=False),
    sa.Column('tarjetas_rojas', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_jugador'], ['jugador.numero_carnet'], ),
    sa.ForeignKeyConstraint(['id_partido'], ['partido.id'], ),
    sa.PrimaryKeyConstraint('id_jugador', 'id_partido')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estado_jugador_partido')
    op.drop_table('partido')
    op.drop_table('jugador_equipo')
    op.drop_table('fase')
    op.drop_table('video')
    op.drop_table('torneo')
    op.drop_table('noticia')
    op.drop_table('jugador')
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.drop_index('ix_equipo_club_categoria')

    op.drop_table('equipo')
    op.drop_table('usuario')
    op.drop_table('temporada')
    op.drop_table('tabla_posiciones')
    op.drop_table('club')
    # ### end Alembic commands ###
