"""add torneo_id and fase_id to partido

Revision ID: b53b0d1fb57a
Revises: 12f7a8781d16
Create Date: 2025-12-14 19:01:29.632615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b53b0d1fb57a'
down_revision = '12f7a8781d16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('torneo_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fase_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'fase', ['fase_id'], ['id'])
        batch_op.create_foreign_key(None, 'torneo', ['torneo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partido', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fase_id')
        batch_op.drop_column('torneo_id')

    # ### end Alembic commands ###
