"""add torneo_id and fase_id to partido

Revision ID: b53b0d1fb57a
Revises: 12f7a8781d16
Create Date: 2025-12-14 19:01:29.632615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b53b0d1fb57a'
down_revision = '12f7a8781d16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('torneo_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fase_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'fase', ['fase_id'], ['id'])
        batch_op.create_foreign_key(None, 'torneo', ['torneo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    op.execute("""
    DO $$
    BEGIN
        IF EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_name='partido' AND column_name='fase_id'
        ) THEN
            ALTER TABLE partido DROP COLUMN fase_id;
        END IF;

        IF EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_name='partido' AND column_name='torneo_id'
        ) THEN
            ALTER TABLE partido DROP COLUMN torneo_id;
        END IF;
    END$$;
    """)

    # ### end Alembic commands ###
