"""Permitir nulos en fecha y hora

Revision ID: be000f547a19
Revises: 6e78f9475670
Create Date: 2025-11-27 10:46:14.320388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be000f547a19'
down_revision = '6e78f9475670'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partido', schema=None) as batch_op:
        batch_op.alter_column('fecha_partido',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partido', schema=None) as batch_op:
        batch_op.alter_column('fecha_partido',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
