"""Agrego campo categoria en tabla posiciones

Revision ID: faa8c5b919e2
Revises: 
Create Date: 2025-10-24 17:18:38.895068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faa8c5b919e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabla_posiciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabla_posiciones', schema=None) as batch_op:
        batch_op.drop_column('categoria')

    # ### end Alembic commands ###
